project:
  type: website
  output-dir: docs
  title: "Ester Alongi"

website:
  title: "Ester Alongi"
  favicon: images/Photo Ester Alongi.jpg
  description: "Ester Alongi is a statistician working on replicability and mediation analysis applied to psychology and genomics research."
  navbar: 
    title: Ester Alongi
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: talks.qmd
        text: Talks
  body-footer: |
    <center>
    <br>
    **Email**:<br>
    [ester.alongi@phd.unipd.it](mailto:ester.alongi@phd.unipd.it)<br>
    <br>
    **Links**:<br>
    [{{< iconify fa6-brands github size=30px >}}](https://github.com/esteralongi)
    [{{< iconify fa6-brands linkedin size=30px >}}](https://www.linkedin.com/in/ester-alongi-4b968815b/)
    [{{< iconify fa6-brands researchgate size=30px >}}](https://www.researchgate.net/profile/Ester-Alongi)
    [{{< iconify fa6-brands orcid size=30px >}}](https://orcid.org/0009-0002-3946-506X)
    </center>
  page-footer:
    left: "© 2026 Ester Alongi. All rights reserved."
    right: 
      - icon: envelope-at
        text: "ester.alongi@phd.unipd.it"
        href: "mailto:ester.alongi@phd.unipd.it"
  site-url: https://esteralongi.github.io/web/

format:
  html:
    theme: [cosmo, styles.css]
    fontsize: 1.1em
    linestretch: 1.6
    max-width: 36em
    backgroundcolor: "#F6F9FB"
    css: styles.css
    toc: false
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px

editor: visual